all: helloWindow.cpp ../glad.c 
	g++ -o helloWindow helloWindow.cpp ../glad.c -lglfw -ldl
clean:
	$(RM) helloWindow                                                                                                    
